import { z } from "zod";
import type { AgentOutputType } from "./constants";

/**
 * Guardrails module — validates and sanitizes agent outputs before
 * they reach the user or trigger downstream actions.
 *
 * Responsibilities:
 * - Structured output enforcement
 * - PII redaction placeholders
 * - Medical disclaimer injection
 * - Output length limits
 */

const MAX_OUTPUT_LENGTH = 4000;

/** Validate that an agent output conforms to the expected shape. */
export function validateOutput(output: unknown): {
  valid: boolean;
  errors: string[];
} {
  const errors: string[] = [];

  if (!output || typeof output !== "object") {
    return { valid: false, errors: ["Output must be a non-null object."] };
  }

  const obj = output as Record<string, unknown>;

  if (!obj.type || !["suggestion", "draft", "prediction", "approved_action"].includes(obj.type as string)) {
    errors.push(`Invalid output type: '${obj.type}'. Must be suggestion|draft|prediction|approved_action.`);
  }

  if (!obj.content) {
    errors.push("Output must have a 'content' field.");
  }

  if (typeof obj.content === "string" && obj.content.length > MAX_OUTPUT_LENGTH) {
    errors.push(`Output content exceeds max length of ${MAX_OUTPUT_LENGTH} chars.`);
  }

  return { valid: errors.length === 0, errors };
}

/** Add medical disclaimer to doctor-facing AI draft outputs. */
export function addMedicalDisclaimer(output: { type: AgentOutputType; content: unknown; disclaimer?: string }) {
  if (output.type === "draft") {
    output.disclaimer =
      "⚠️ AI-GENERATED DRAFT — This content was generated by AI and must be reviewed and confirmed by the doctor before being saved to the patient record.";
  }
  return output;
}

/**
 * Redact patterns that look like PII from text.
 * This is a placeholder — production systems should use a dedicated
 * PII detection service or regex library.
 */
export function redactPII(text: string): string {
  // Redact email patterns
  let redacted = text.replace(/[\w.+-]+@[\w-]+\.[\w.]+/g, "[EMAIL_REDACTED]");
  // Redact phone patterns (basic)
  redacted = redacted.replace(/\b\d{10,}\b/g, "[PHONE_REDACTED]");
  // Redact Aadhaar-like patterns (12-digit)
  redacted = redacted.replace(/\b\d{4}\s?\d{4}\s?\d{4}\b/g, "[ID_REDACTED]");
  return redacted;
}
